package user;


import ivan.LOGINF;
import Admin.AdminDashboardd;
import config.Session;
import static config.Session.getInstance;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class AccountDetails extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardd
     */
    public AccountDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maindesktop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        acc_ln = new javax.swing.JLabel();
        acc_fn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlabl2 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jlabl1 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jlabel3 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        jlabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maindesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ACCOUNT INFORMATION");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 360, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(740, 10, 100, 30);

        iddisplay.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(51, 51, 51));
        iddisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddisplay.setText("(SID)");
        jPanel2.add(iddisplay);
        iddisplay.setBounds(380, 0, 120, 50);

        maindesktop.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        navbar.setBackground(new java.awt.Color(0, 204, 204));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsfolder/icons8-admin-100.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 108, 84));

        navbar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 110));

        acc_ln.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_ln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln.setText("User");
        navbar.add(acc_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, 30));

        acc_fn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fn.setText("acc fn");
        navbar.add(acc_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 30));

        maindesktop.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 260));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabl2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl2.setForeground(new java.awt.Color(255, 255, 255));
        jlabl2.setText("First Name :");
        jlabl2.setToolTipText("");
        jPanel1.add(jlabl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 30));

        fn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        fn.setAutoscrolls(false);
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel1.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 310, 30));

        jlabl1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl1.setForeground(new java.awt.Color(255, 255, 255));
        jlabl1.setText("Last Name:");
        jlabl1.setToolTipText("");
        jPanel1.add(jlabl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 310, 30));

        ln.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ln.setAutoscrolls(false);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel1.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 310, -1));

        jlabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel2.setText("Email:");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, 30));

        em.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        em.setAutoscrolls(false);
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 310, 30));

        jlabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(255, 255, 255));
        jlabel3.setText("User Name:");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 310, 30));

        un.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        un.setAutoscrolls(false);
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel1.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 310, 30));

        jlabel8.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(255, 255, 255));
        jlabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel8.setText("Change Pass");
        jlabel8.setToolTipText("");
        jlabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 170, 30));

        maindesktop.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 710, 240));

        getContentPane().add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 870, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            Session sess = Session.getInstance();
        
            
            
             if(sess.getSid()==0){
            JOptionPane.showMessageDialog(null,"No account found, Login First!");
            LOGINF If = new LOGINF();
            If.setVisible(true);
            this.dispose();
        }else{
            iddisplay.setText("ID: "+sess.getSid());
            acc_fn.setText(""+sess.getFname());
            acc_ln.setText(""+sess.getLname());
            fn.setText(""+sess.getFname());
            ln.setText(""+sess.getLname());
            em.setText(""+sess.getEmail());
            un.setText(""+sess.getUsername());
             }
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        userDashboard udb = new userDashboard();
        udb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void jlabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel8MouseClicked
            ChangePass cp = new ChangePass();
            cp.setVisible(true);
            this.dispose();           
    }//GEN-LAST:event_jlabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_fn;
    private javax.swing.JLabel acc_ln;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabl1;
    private javax.swing.JLabel jlabl2;
    private javax.swing.JTextField ln;
    private javax.swing.JPanel maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
