package user;
import ivan.LOGINF;
import Admin.AdminDashboardd;
import config.Session;
import static config.Session.getInstance;
import config.dbConnector;
import config.passwordHasher;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class ChangePass extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboardd
     */
    public ChangePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maindesktop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iddisplay = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        acc_ln = new javax.swing.JLabel();
        acc_fn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlabel3 = new javax.swing.JLabel();
        conpass = new javax.swing.JTextField();
        jlabel7 = new javax.swing.JLabel();
        oldpass = new javax.swing.JTextField();
        jlabel6 = new javax.swing.JLabel();
        newpass = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maindesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CHANGE PASS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 210, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGOUT");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(500, 10, 100, 30);

        iddisplay.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(51, 51, 51));
        iddisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iddisplay.setText("(SID)");
        jPanel2.add(iddisplay);
        iddisplay.setBounds(230, 0, 120, 50);

        maindesktop.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        navbar.setBackground(new java.awt.Color(0, 204, 204));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsfolder/icons8-admin-100.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 108, 84));

        navbar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 110));

        acc_ln.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_ln.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ln.setText("User");
        navbar.add(acc_ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 30));

        acc_fn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_fn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_fn.setText("acc fn");
        navbar.add(acc_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 30));

        maindesktop.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 350));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(255, 255, 255));
        jlabel3.setText("Confirm Pass:");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 30));

        conpass.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        conpass.setAutoscrolls(false);
        conpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpassActionPerformed(evt);
            }
        });
        jPanel1.add(conpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 280, 30));

        jlabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(255, 255, 255));
        jlabel7.setText("Type old pass:");
        jPanel1.add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        oldpass.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        oldpass.setAutoscrolls(false);
        oldpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpassActionPerformed(evt);
            }
        });
        jPanel1.add(oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 280, 30));

        jlabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(255, 255, 255));
        jlabel6.setText("Enter new Pass:");
        jPanel1.add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 30));

        newpass.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        newpass.setAutoscrolls(false);
        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        jPanel1.add(newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 280, 30));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SAVE");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 10, 100, 30);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SAVE");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(0, 10, 100, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 0, 0);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 100, 50));

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BACK");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 100, 50));

        maindesktop.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 510, 350));

        getContentPane().add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 670, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           Session sess = Session.getInstance();
             int s_id = sess.getSid();   
            
             if(sess.getSid()==0){
            JOptionPane.showMessageDialog(null,"No account found, Login First!");
            LOGINF If = new LOGINF();
            If.setVisible(true);
            this.dispose();
        }else{
            acc_fn.setText(""+sess.getFname());
            acc_ln.setText(""+sess.getLname());
             }
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
          LOGINF If = new LOGINF();
          JOptionPane.showMessageDialog(null," Logged-out ");
          If.setVisible(true);
          this.dispose();  
    }//GEN-LAST:event_jLabel5MouseClicked

    private void conpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpassActionPerformed

    private void oldpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpassActionPerformed

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
      
      try {   
    dbConnector dbc = new dbConnector();
    Session sess = Session.getInstance();

    String query = "SELECT * FROM tbl_student WHERE s_id = '" + sess.getSid() + "'";
    ResultSet rs = dbc.getData(query);
    
    if (rs.next()) {
        String olddpass = rs.getString("s_password");
        String storedSports= rs.getString("s_favsports");

        String oldhash = passwordHasher.hashPassword(oldpass.getText());

        if (olddpass.equals(oldhash)) {
            String studentstoredSports = JOptionPane.showInputDialog(null, "What is your sports?");

            if (storedSports != null && storedSports.equalsIgnoreCase(storedSports)) {
    
                String npass = passwordHasher.hashPassword(newpass.getText());

                String checkPasswordQuery = "SELECT s_password FROM tbl_student WHERE s_id = '" + sess.getSid() + "'";
                ResultSet rsHistory = dbc.getData(checkPasswordQuery);

                boolean isPasswordUsedBefore = false;
                
                while (rsHistory.next()) {
                    String oldPasswordHistory = rsHistory.getString("s_password");
                    if (passwordHasher.hashPassword(newpass.getText()).equals(oldPasswordHistory)) {
                        isPasswordUsedBefore = true;
                        break;
                    }
                }
   
                if (isPasswordUsedBefore) {
                    JOptionPane.showMessageDialog(null, "You cannot reuse an old password.");
                } else {
                    
              dbc.updateData("UPDATE tbl_student SET s_password = '" + npass + "' WHERE s_id = '" + sess.getSid() + "'");
                 
                    dbc.updateData("INSERT INTO tbl_student_password_history (s_id, s_password) VALUES ('" + sess.getSid() + "', '" + olddpass + "')");

                    JOptionPane.showMessageDialog(null, "Password Successfully Updated!");


                    LOGINF lf = new LOGINF();
                    lf.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "The answer to your sports is incorrect.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Old Password is Incorrect");
        }
    }   
} catch (SQLException | NoSuchAlgorithmException ex) {
    System.out.println("" + ex);
}
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
         AccountDetails ad = new AccountDetails();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_fn;
    private javax.swing.JLabel acc_ln;
    private javax.swing.JTextField conpass;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JPanel maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField oldpass;
    // End of variables declaration//GEN-END:variables
}
