package user;
import Admin.TeacherForm;

import config.PanelPrinter;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class GradesPrinting extends javax.swing.JFrame {

     

    /**
     * Creates new form individualPrinting
     */
    public GradesPrinting() {
        initComponents();
    }
    
    public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            // Read the image file
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
            // Get the original width and height of the image
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
            // Calculate the new height based on the desired width and the aspect ratio
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }
    
    
    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
   Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        tid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        yr = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dep = new javax.swing.JLabel();
        gid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pre = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        prefi = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mid = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ss3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        fi = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("GRADE PRINTING");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 250, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(650, 0, 110, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 60);

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRADE TRACKER SYSTEM");
        page.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 410, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ivan villarino");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 230, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 855, 16));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Teacher ID:");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        tid.setBackground(new java.awt.Color(51, 51, 51));
        tid.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        tid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Student Name:");
        page.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 30));

        sname.setBackground(new java.awt.Color(51, 51, 51));
        sname.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        sname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 30));

        yr.setBackground(new java.awt.Color(51, 51, 51));
        yr.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        yr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Year:");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 30));

        c.setBackground(new java.awt.Color(51, 51, 51));
        c.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        c.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Department:");
        page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 30));

        dep.setBackground(new java.awt.Color(51, 51, 51));
        dep.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        dep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 160, 30));

        gid.setBackground(new java.awt.Color(51, 51, 51));
        gid.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        gid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(gid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 30));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("GRADE ID:");
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Course");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 100, 30));

        name7.setBackground(new java.awt.Color(51, 51, 51));
        name7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        name7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 349, 160, 30));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Prelim:");
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 30));

        pre.setBackground(new java.awt.Color(51, 51, 51));
        pre.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        pre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 30));

        image.setBackground(new java.awt.Color(0, 0, 0));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 350, 360));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-scorecard-64.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 68));

        page.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 90));

        prefi.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        prefi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(prefi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 160, 30));

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Prefinal:");
        page.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, 30));

        mid.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        mid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 160, 30));

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Midterm:");
        page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 30));

        ss3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(ss3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 160, 30));

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 30));

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Final:");
        page.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 100, 30));

        fi.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(fi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 160, 30));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Status:");
        page.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 100, 30));

        s.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        s.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 160, 30));

        jPanel1.add(page);
        page.setBounds(30, 120, 700, 570);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 80, 90, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        TeacherForm tf = new TeacherForm();
        tf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JPanel myPanel = new JPanel();
         PanelPrinter pPrint = new PanelPrinter(page);
         pPrint.printPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesPrinting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel c;
    public javax.swing.JLabel dep;
    public javax.swing.JLabel fi;
    public javax.swing.JLabel gid;
    public javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel mid;
    public javax.swing.JLabel name7;
    private javax.swing.JPanel page;
    public javax.swing.JLabel pre;
    public javax.swing.JLabel prefi;
    public javax.swing.JLabel s;
    public javax.swing.JLabel sname;
    public javax.swing.JLabel ss3;
    public javax.swing.JLabel tid;
    public javax.swing.JLabel yr;
    // End of variables declaration//GEN-END:variables
}
