package user;


import Admin.TeacherForm;
import user.AccountDetails;
import ivan.LOGINF;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ivan
 */
public class GradesPage extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public GradesPage() {
        initComponents();
    }
       Color navcolor = new Color(0,204,204);
        Color hovercolor = new Color(0,153,153);
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maindesktop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        din = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        acc_name = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gTable = new javax.swing.JTable();
        acc_name3 = new javax.swing.JLabel();
        acc_name4 = new javax.swing.JLabel();
        jlabl3 = new javax.swing.JLabel();
        jlabl2 = new javax.swing.JLabel();
        jlabl4 = new javax.swing.JLabel();
        jlabl8 = new javax.swing.JLabel();
        jlabl9 = new javax.swing.JLabel();
        gid = new javax.swing.JTextField();
        sid = new javax.swing.JTextField();
        tid = new javax.swing.JTextField();
        dep = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        jlabel8 = new javax.swing.JLabel();
        jlabl13 = new javax.swing.JLabel();
        jlabl12 = new javax.swing.JLabel();
        jlabl11 = new javax.swing.JLabel();
        jlabl10 = new javax.swing.JLabel();
        pre = new javax.swing.JTextField();
        mid = new javax.swing.JTextField();
        prefi = new javax.swing.JTextField();
        fi = new javax.swing.JTextField();
        s = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maindesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(940, 0, 100, 60);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("GRADE FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 200, 40);

        maindesktop.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1040, 60));

        din.setBackground(new java.awt.Color(0, 204, 204));
        din.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsfolder/icons8-admin-100.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 70));

        din.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 90));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        din.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        jButton2.setBackground(new java.awt.Color(0, 51, 102));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("UPDATE");
        din.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, 30));

        jButton3.setBackground(new java.awt.Color(0, 51, 102));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setText("DELETE");
        din.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 30));

        acc_name.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("ADMIN");
        din.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 140, 40));

        maindesktop.add(din, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 550));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 400, 470));

        acc_name3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-32.png"))); // NOI18N
        acc_name3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_name3MouseClicked(evt);
            }
        });
        jPanel1.add(acc_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 60, 40));

        acc_name4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_name4.setForeground(new java.awt.Color(255, 255, 255));
        acc_name4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        acc_name4.setText("GRADES TABLE:");
        jPanel1.add(acc_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 190, 40));

        jlabl3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl3.setForeground(new java.awt.Color(255, 255, 255));
        jlabl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl3.setText("grade ID:");
        jlabl3.setToolTipText("");
        jPanel1.add(jlabl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        jlabl2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl2.setForeground(new java.awt.Color(255, 255, 255));
        jlabl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl2.setText("Student ID:");
        jlabl2.setToolTipText("");
        jPanel1.add(jlabl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 30));

        jlabl4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl4.setForeground(new java.awt.Color(255, 255, 255));
        jlabl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl4.setText("Teacher ID:");
        jlabl4.setToolTipText("");
        jPanel1.add(jlabl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 30));

        jlabl8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl8.setForeground(new java.awt.Color(255, 255, 255));
        jlabl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl8.setText("Department:");
        jlabl8.setToolTipText("");
        jPanel1.add(jlabl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 30));

        jlabl9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl9.setForeground(new java.awt.Color(255, 255, 255));
        jlabl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl9.setText("Course:");
        jlabl9.setToolTipText("");
        jPanel1.add(jlabl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, 30));

        gid.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        gid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gid.setAutoscrolls(false);
        gid.setEnabled(false);
        gid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gidActionPerformed(evt);
            }
        });
        jPanel1.add(gid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 260, 40));

        sid.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        sid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sid.setAutoscrolls(false);
        sid.setEnabled(false);
        sid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidActionPerformed(evt);
            }
        });
        jPanel1.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, 40));

        tid.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tid.setAutoscrolls(false);
        tid.setEnabled(false);
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        jPanel1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 260, 40));

        dep.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        dep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dep.setAutoscrolls(false);
        dep.setEnabled(false);
        dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depActionPerformed(evt);
            }
        });
        jPanel1.add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, 40));

        c.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c.setAutoscrolls(false);
        c.setEnabled(false);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 260, 40));

        jlabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(255, 255, 255));
        jlabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabel8.setText("Status:");
        jlabel8.setToolTipText("");
        jPanel1.add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 70, 40));

        jlabl13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl13.setForeground(new java.awt.Color(255, 255, 255));
        jlabl13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl13.setText("Final:");
        jlabl13.setToolTipText("");
        jPanel1.add(jlabl13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 70, 30));

        jlabl12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl12.setForeground(new java.awt.Color(255, 255, 255));
        jlabl12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl12.setText("prefinal: ");
        jlabl12.setToolTipText("");
        jPanel1.add(jlabl12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 90, 30));

        jlabl11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl11.setForeground(new java.awt.Color(255, 255, 255));
        jlabl11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl11.setText("MIdterm:");
        jlabl11.setToolTipText("");
        jPanel1.add(jlabl11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 30));

        jlabl10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl10.setForeground(new java.awt.Color(255, 255, 255));
        jlabl10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabl10.setText("Prelim:");
        jlabl10.setToolTipText("");
        jPanel1.add(jlabl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 70, 30));

        pre.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pre.setAutoscrolls(false);
        pre.setEnabled(false);
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });
        jPanel1.add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 260, 40));

        mid.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        mid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mid.setAutoscrolls(false);
        mid.setEnabled(false);
        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        jPanel1.add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 260, 40));

        prefi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        prefi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prefi.setAutoscrolls(false);
        prefi.setEnabled(false);
        prefi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefiActionPerformed(evt);
            }
        });
        jPanel1.add(prefi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 260, 40));

        fi.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        fi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fi.setAutoscrolls(false);
        fi.setEnabled(false);
        fi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiActionPerformed(evt);
            }
        });
        jPanel1.add(fi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 260, 40));

        s.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Passed", "Failed", " " }));
        s.setEnabled(false);
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 260, 40));

        maindesktop.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 900, 550));

        getContentPane().add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 1050, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    Session sess = Session.getInstance();
             int s_id = sess.getSid();   
            
             if(sess.getSid()==0){
            JOptionPane.showMessageDialog(null,"No account, Login First!");
            LOGINF If = new LOGINF();
            If.setVisible(true);
            this.dispose();
        }else{
            acc_name.setText(""+sess.getFname());

        }    
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       TeacherForm tfm = new TeacherForm();
       tfm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void gTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gTableMouseClicked
      
    }//GEN-LAST:event_gTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Session sess = Session.getInstance();
       if(gid.getText().isEmpty()||sid.getText().isEmpty()||tid.getText().isEmpty()     
            ||dep.getText().isEmpty()||c.getText().isEmpty()||pre.getText().isEmpty()
            ||mid.getText().isEmpty()||prefi.getText().isEmpty()||fi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are required!");
        }else{
            dbConnector dbc = new dbConnector();
        String sql = "INSERT INTO tbl_grade(s_id, t_id, Department, Course ,Prelim, Midterm, Prefinal, Final, Status, Image)"
            + " VALUES('"+sess.getSid()+"','" + tid.getText() + "','" 
            + dep.getText() + "','" +c.getText()+"','"
            + pre.getText() + "', '"+ mid.getText() +"','"
            + prefi.getText() +"','"+ fi.getText() +"','"+s.getSelectedItem()+"','','')";
            JOptionPane.showMessageDialog(null,"Grades Added!");

      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void acc_name3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_name3MouseClicked
       this.dispose();
       UserTable gt = new UserTable();
       gt.setVisible(true);
    }//GEN-LAST:event_acc_name3MouseClicked

    private void gidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gidActionPerformed

    private void sidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidActionPerformed

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preActionPerformed

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed

    private void prefiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prefiActionPerformed

    private void fiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_name;
    private javax.swing.JLabel acc_name3;
    private javax.swing.JLabel acc_name4;
    public javax.swing.JTextField c;
    public javax.swing.JTextField dep;
    private javax.swing.JPanel din;
    public javax.swing.JTextField fi;
    private javax.swing.JTable gTable;
    public javax.swing.JTextField gid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabl10;
    private javax.swing.JLabel jlabl11;
    private javax.swing.JLabel jlabl12;
    private javax.swing.JLabel jlabl13;
    private javax.swing.JLabel jlabl2;
    private javax.swing.JLabel jlabl3;
    private javax.swing.JLabel jlabl4;
    private javax.swing.JLabel jlabl8;
    private javax.swing.JLabel jlabl9;
    private javax.swing.JPanel maindesktop;
    public javax.swing.JTextField mid;
    public javax.swing.JTextField pre;
    public javax.swing.JTextField prefi;
    public javax.swing.JComboBox<String> s;
    public javax.swing.JTextField sid;
    public javax.swing.JTextField tid;
    // End of variables declaration//GEN-END:variables
}
