package user;


import user.usersForm;
import Admin.AdminDashboardd;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import static java.awt.Color.blue;
import static java.awt.Color.gray;
import static java.awt.Color.green;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ivan
 */
public class productForm extends javax.swing.JFrame {

    /**
     * Creates new form usersForm
     */
    public productForm() {
        initComponents();
        displayData();
    
    }
    
    boolean checkadd = true; 
    
        Color navcolor = new Color(0,204,204);
        Color hovercolor = new Color(0,51,102);
    
    public void displayData(){
        try{
            
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT p_id, p_name ,p_status FROM tbl_product");
            pTable.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        }catch(SQLException ex){
            System.out.println("Errors:"+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maindesktop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        acc_lname = new javax.swing.JLabel();
        acc_lname1 = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        print = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        pstat = new javax.swing.JComboBox<>();
        pid = new javax.swing.JTextField();
        pprice = new javax.swing.JTextField();
        jlabl3 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jlabl1 = new javax.swing.JLabel();
        jlabl2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maindesktop.setBackground(new java.awt.Color(0, 51, 102));
        maindesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("PRODUCT FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 290, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(800, 0, 100, 50);

        maindesktop.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 50));

        navbar.setBackground(new java.awt.Color(0, 204, 204));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsfolder/icons8-user-group-skin-type-7-100.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 70));

        navbar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 70));

        acc_lname.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname.setText("USERS");
        navbar.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 160, 20));

        acc_lname1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acc_lname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname1.setText("Current User:");
        navbar.add(acc_lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 30));

        acc_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        navbar.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 20));

        print.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        print.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        print.setText("PRINT");
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        navbar.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 160, 50));

        add.setBackground(new java.awt.Color(0, 204, 204));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addlabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("ADD");
        addlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addlabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addlabelMouseExited(evt);
            }
        });
        add.add(addlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 30));

        navbar.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, 50));

        clear.setBackground(new java.awt.Color(0, 204, 204));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLEAR");
        clear.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 30));

        navbar.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 160, 50));

        update.setBackground(new java.awt.Color(0, 204, 204));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UPDATE");
        update.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 20));

        navbar.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 40));

        maindesktop.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 550));

        pTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pTable);

        maindesktop.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 300, 510));

        pstat.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pstat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Ouf of Stock", " " }));
        pstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstatActionPerformed(evt);
            }
        });
        maindesktop.add(pstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 250, 40));

        pid.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pid.setAutoscrolls(false);
        pid.setEnabled(false);
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        maindesktop.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 250, 30));

        pprice.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pprice.setAutoscrolls(false);
        pprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppriceActionPerformed(evt);
            }
        });
        maindesktop.add(pprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 250, 30));

        jlabl3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl3.setForeground(new java.awt.Color(255, 255, 255));
        jlabl3.setText("Product ID:");
        jlabl3.setToolTipText("");
        maindesktop.add(jlabl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 140, 30));

        jlabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(255, 255, 255));
        jlabel8.setText("User Status:");
        jlabel8.setToolTipText("");
        maindesktop.add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 140, 40));

        jlabl1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl1.setForeground(new java.awt.Color(255, 255, 255));
        jlabl1.setText("Price:");
        jlabl1.setToolTipText("");
        maindesktop.add(jlabl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 140, 30));

        jlabl2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl2.setForeground(new java.awt.Color(255, 255, 255));
        jlabl2.setText(" Name :");
        jlabl2.setToolTipText("");
        maindesktop.add(jlabl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 140, 30));

        pname.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        pname.setAutoscrolls(false);
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        maindesktop.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 250, 30));

        jPanel1.setLayout(null);
        jPanel1.add(image);
        image.setBounds(40, 20, 310, 180);

        maindesktop.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 390, 220));

        select.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        select.setText("SELECT");
        select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectMouseClicked(evt);
            }
        });
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        maindesktop.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 140, 40));

        remove.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        remove.setText("REMOVE");
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        maindesktop.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 130, 40));

        getContentPane().add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
 
    }//GEN-LAST:event_userMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        AdminDashboardd adb = new AdminDashboardd();
        adb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       Session sess = new Session();
       acc_id.setText(""+sess.getSid());
    }//GEN-LAST:event_formWindowActivated

    private void pstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pstatActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void ppriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppriceActionPerformed

    private void selectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selectMouseClicked

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
   
    }//GEN-LAST:event_selectActionPerformed

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_removeMouseClicked

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
       
    }//GEN-LAST:event_removeActionPerformed

    private void pTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTableMouseClicked
         int rowindex = pTable.getSelectedRow();
       
       if(rowindex < 0){
         JOptionPane.showMessageDialog(null,"Please select an item");
       }else{
            try{
            dbConnector dbc = new dbConnector();
            TableModel tbl = pTable.getModel();
            
            ResultSet rs = dbc.getData("SELECT * FROM tbl_product WHERE p_id ='"+tbl.getValueAt(rowindex,0)+"'");
            if(rs.next()){
                
            pid.setText(""+rs.getInt("p_id"));
            pname.setText(""+rs.getString("p_name"));
            pprice.setText(""+rs.getString("p_price"));
            pstat.setSelectedItem(""+rs.getString("p_status"));
            add.setEnabled(false);
            addlabel.setForeground(green);
            checkadd = false;
            }
                            
        }catch(SQLException ex){
              System.out.println(""+ex);
            }
       }
  
    }//GEN-LAST:event_pTableMouseClicked

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
             
        
    }//GEN-LAST:event_printMouseClicked

    private void addlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabelMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        if(checkadd){
            
            if(pname.getText().isEmpty()||pprice.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All Fields are required!");
          }else{
               dbConnector dbc = new dbConnector();
         dbc.insertData("INSERT INTO tbl_product(p_name, p_pprice, p_status, p_image)VALUES"
            + "('"+pname.getText()+"',"
               + "'"+pprice.getText()+"','"+pstat.getSelectedItem()+"','')");
            JOptionPane.showMessageDialog(null,"Successfully Added!");
            displayData();
            checkadd = true;
            addlabel.setForeground(blue);
            pid.setText("");
            pname.setText("");
            pprice.setText("");
            pstat.setSelectedIndex(0);
            
            } 
            
        }else{
         JOptionPane.showMessageDialog(null,"Clear The Field First!");
            }
        
    }//GEN-LAST:event_addMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        checkadd = true;
        addlabel.setForeground(blue);
        pid.setText("");
        pname.setText("");
        pprice.setText("");
        pstat.setSelectedIndex(0);
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
      clear.setBackground(hovercolor);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(navcolor);
    }//GEN-LAST:event_clearMouseExited

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print.setBackground(hovercolor);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
      print.setBackground(navcolor);
    }//GEN-LAST:event_printMouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(hovercolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
          update.setBackground(hovercolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
          update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void addlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseEntered
            add.setBackground(hovercolor);
    }//GEN-LAST:event_addlabelMouseEntered

    private void addlabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseExited
         add.setBackground(navcolor);
    }//GEN-LAST:event_addlabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel acc_lname1;
    private javax.swing.JPanel add;
    private javax.swing.JLabel addlabel;
    private javax.swing.JPanel clear;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabl1;
    private javax.swing.JLabel jlabl2;
    private javax.swing.JLabel jlabl3;
    private javax.swing.JPanel maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JTable pTable;
    public javax.swing.JTextField pid;
    public javax.swing.JTextField pname;
    public javax.swing.JTextField pprice;
    private javax.swing.JLabel print;
    public javax.swing.JComboBox<String> pstat;
    public javax.swing.JButton remove;
    public javax.swing.JButton select;
    private javax.swing.JPanel update;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
