package user;


import Admin.individualPrinting;
import Admin.createUserForm;
import config.Session;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ivan
 */
public class usersForm extends javax.swing.JFrame {

    /**
     * Creates new form usersForm
     */
    public usersForm() {
        initComponents();
        displayData();
    
    }
    
        Color navcolor = new Color(0,204,204);
        Color hovercolor = new Color(0,51,102);
    
    public void displayData(){
        try{
            
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT s_id, s_fname, s_lname, s_email,s_status FROM tbl_student");
            studentsTable.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        }catch(SQLException ex){
            System.out.println("Errors:"+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maindesktop = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        p_add = new javax.swing.JPanel();
        acc_lname2 = new javax.swing.JLabel();
        acc_lname = new javax.swing.JLabel();
        p_edit = new javax.swing.JPanel();
        acc_lname3 = new javax.swing.JLabel();
        print = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        acc_lname1 = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maindesktop.setBackground(new java.awt.Color(0, 51, 102));
        maindesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("USERS FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 10, 290, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(800, 0, 100, 50);

        maindesktop.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 50));

        navbar.setBackground(new java.awt.Color(0, 204, 204));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsfolder/icons8-user-group-skin-type-7-100.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 70));

        navbar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 70));

        p_add.setBackground(new java.awt.Color(0, 204, 204));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        acc_lname2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_lname2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname2.setText("ADD");
        p_add.add(acc_lname2);
        acc_lname2.setBounds(0, 10, 160, 20);

        navbar.add(p_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, 40));

        acc_lname.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname.setText("USERS");
        navbar.add(acc_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 160, 20));

        p_edit.setBackground(new java.awt.Color(0, 204, 204));
        p_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_editMouseExited(evt);
            }
        });
        p_edit.setLayout(null);

        acc_lname3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        acc_lname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname3.setText("EDIT");
        p_edit.add(acc_lname3);
        acc_lname3.setBounds(0, 10, 160, 20);

        navbar.add(p_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 160, 40));

        print.setBackground(new java.awt.Color(0, 204, 204));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        print.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRINT");
        print.add(jLabel2);
        jLabel2.setBounds(0, 10, 160, 20);

        navbar.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 160, 40));

        acc_lname1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acc_lname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_lname1.setText("Current User:");
        navbar.add(acc_lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 30));

        acc_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        navbar.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 160, 20));

        maindesktop.add(navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 360));

        jScrollPane1.setViewportView(studentsTable);

        maindesktop.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 730, 340));

        getContentPane().add(maindesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
 
    }//GEN-LAST:event_userMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
     int rowindex = studentsTable.getSelectedRow();
       
       if(rowindex < 0){
         JOptionPane.showMessageDialog(null,"Please select an item");
       }else{
            try{
            dbConnector dbc = new dbConnector();
            TableModel tbl = studentsTable.getModel();
            
            ResultSet rs = dbc.getData("SELECT * FROM tbl_student WHERE s_id = '"+tbl.getValueAt(rowindex,0)+"'");
            if(rs.next()){
            createUserForm crf = new createUserForm();
            crf.sid.setText(""+rs.getInt("s_id"));
            crf.fn.setText(""+rs.getString("s_fname"));
            crf.ln.setText(""+rs.getString("s_lname"));
            crf.em.setText(""+rs.getString("s_email"));
            crf.un.setText(""+rs.getString("s_username"));
            crf.ps.setText(""+rs.getString("s_password"));
            crf.gn.setText(""+rs.getString("s_gender"));
            crf.stat.setText(""+rs.getString("s_status"));
            crf.st.setSelectedItem(""+rs.getString("s_type"));
            crf.ss.setSelectedItem(""+rs.getString("s_status"));
            crf.image.setIcon(crf.ResizeImage(rs.getString("s_image"),null,crf.image));
            crf.oldpath = rs.getString("s_image");
            crf.path = rs.getString("s_image");
            crf.destination = rs.getString("s_image");
            crf.add.setEnabled(false);
            crf.update.setEnabled(true);
            crf.setVisible(true);
            
            if( rs.getString("s_image").isEmpty()){
                crf.select.setEnabled(true);
                crf.remove.setEnabled(false);                
            }else{
                crf.select.setEnabled(false);
                crf.remove.setEnabled(true);      
            }
            
                this.dispose();
            }           
        }catch(SQLException ex){
              System.out.println(""+ex);
            }
       }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     Session sess = Session.getInstance();
     acc_id.setText(""+sess.getSid());  
    }//GEN-LAST:event_formWindowActivated

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
      p_add.setBackground(hovercolor);
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
      p_add.setBackground(navcolor);
    }//GEN-LAST:event_p_addMouseExited

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
       createUserForm crf = new createUserForm();
       crf.remove.setEnabled(false);
       crf.select.setEnabled(true);
       crf.setVisible(true);
       this.dispose();
     
    }//GEN-LAST:event_p_addMouseClicked

    private void p_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseClicked
       int rowindex = studentsTable.getSelectedRow();
       
       if(rowindex < 0){
         JOptionPane.showMessageDialog(null,"Please select an item");
       }else{
            try{
            dbConnector dbc = new dbConnector();
            TableModel tbl = studentsTable.getModel();
            
            ResultSet rs = dbc.getData("SELECT * FROM tbl_student WHERE s_id = '"+tbl.getValueAt(rowindex,0)+"'");
            if(rs.next()){
            createUserForm crf = new createUserForm();
            crf.sid.setText(""+rs.getInt("s_id"));
            crf.fn.setText(""+rs.getString("s_fname"));
            crf.ln.setText(""+rs.getString("s_lname"));
            crf.em.setText(""+rs.getString("s_email"));
            crf.un.setText(""+rs.getString("s_username"));
            crf.ps.setText(""+rs.getString("s_email"));
            crf.gn.setText(""+rs.getString("s_gender"));
            crf.st.setSelectedItem(""+rs.getString("s_type"));
            crf.ss.setSelectedItem(""+rs.getString("s_status"));
            crf.image.setIcon(crf.ResizeImage(rs.getString("s_image"),null,crf.image));
            crf.oldpath = rs.getString("s_image");
            crf.path = rs.getString("s_image");
            crf.destination = rs.getString("s_image");
            crf.add.setEnabled(false);
            crf.update.setEnabled(true);
            crf.setVisible(true);   
            
            
            if(rs.getString("s_image").isEmpty()){
            crf.select.setEnabled(true);
            crf.remove.setEnabled(false);
            }else{
            crf.select.setEnabled(false);
            crf.remove.setEnabled(true);
            }
                  this.dispose();
            }           
        }catch(SQLException ex){
              System.out.println(""+ex);
            }
       }
       
          
    }//GEN-LAST:event_p_editMouseClicked

    private void p_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseEntered
       p_edit.setBackground(hovercolor);
    }//GEN-LAST:event_p_editMouseEntered

    private void p_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_editMouseExited
       p_edit.setBackground(navcolor);
    }//GEN-LAST:event_p_editMouseExited

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
      
      individualPrinting ip = new individualPrinting();
       ip.setVisible(true);
       

    }//GEN-LAST:event_printMouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print.setBackground(hovercolor);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
         print.setBackground(navcolor);
    }//GEN-LAST:event_printMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel acc_lname;
    private javax.swing.JLabel acc_lname1;
    private javax.swing.JLabel acc_lname2;
    private javax.swing.JLabel acc_lname3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel maindesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel p_add;
    private javax.swing.JPanel p_edit;
    private javax.swing.JPanel print;
    private javax.swing.JTable studentsTable;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
