package ivan;

import ivan.LOGINF;
import config.dbConnector;
import config.passwordHasher;
import java.awt.BasicStroke;
import java.awt.Color;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import static javax.swing.text.html.HTML.Tag.OPTION;


public class Registerform extends javax.swing.JFrame {

    /**
     * Creates new form LOGINF
     */
    public Registerform() {
        initComponents();
        
       }
        
       public String destination;
               
        public static String email,stname;
       
        public boolean duplicateCheck(){
        
         dbConnector dbc = new dbConnector();
            
         try{
           String query = ("SELECT * FROM tbl_student WHERE s_username = '"+un.getText()+"'OR s_email ='" + ""+em.getText()+"'");
           ResultSet resultSet = dbc.getData(query);
         
           if(resultSet.next()){
                 email = resultSet.getString("s_email");
                 if(email.equals(em.getText())){
                  JOptionPane.showMessageDialog(null,"Email is Already Used!");
                  em.setText("");   
                 }
                 
                 stname = resultSet.getString("s_username");
                 if(stname.equals(un.getText())){
                  JOptionPane.showMessageDialog(null,"User is Already Used!");
                  un.setText(""); 
                 }
               
                 return true;
                 
           }else{
                 return false;
           }
           
         }catch(SQLException ex){
         System.out.println(""+ex);
         return false;
                 
         }
        }
    
    
    Color hover = new Color (0,204,204);
     Color defbutton = new Color (0,51,102);
        
        
        Border empty = BorderFactory.createEmptyBorder();
        
        
    void buttonBorderAnimation(JPanel panel){
        panel.setBackground(hover);
        panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
     
    }    
    void buttonDefaultColor(JPanel panel){
         panel.setBackground(defbutton);
         panel.setBorder(empty);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jlabel3 = new javax.swing.JLabel();
        gn = new javax.swing.JTextField();
        jlabl1 = new javax.swing.JLabel();
        ss = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        jlabel5 = new javax.swing.JLabel();
        st = new javax.swing.JComboBox<>();
        jlabl2 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jlabel6 = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        name4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ivan/gradeess.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, 130));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ivan/trackerrrr.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 280, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SYSTEM");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 90, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 370, 600);

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Registration From");
        jPanel5.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        ln.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ln.setAutoscrolls(false);
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel5.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, -1));

        jlabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(255, 255, 255));
        jlabel3.setText("User Name:");
        jPanel5.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 20));

        gn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        gn.setAutoscrolls(false);
        gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnActionPerformed(evt);
            }
        });
        jPanel5.add(gn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 310, 30));

        jlabl1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl1.setForeground(new java.awt.Color(255, 255, 255));
        jlabl1.setText("Last Name:");
        jlabl1.setToolTipText("");
        jPanel5.add(jlabl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 310, 20));

        ss.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ss.setAutoscrolls(false);
        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });
        jPanel5.add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 310, 30));

        jlabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel2.setText("Email:");
        jPanel5.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 20));

        jlabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(255, 255, 255));
        jlabel4.setText("Password :");
        jPanel5.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 310, 20));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Already Have an Account? Click Here to Login");
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));
        jPanel5.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 310, 30));

        jlabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(255, 255, 255));
        jlabel5.setText("Account Type:");
        jlabel5.setToolTipText("");
        jPanel5.add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 320, 20));

        st.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel5.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 310, 30));

        jlabl2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabl2.setForeground(new java.awt.Color(255, 255, 255));
        jlabl2.setText("First Name :");
        jlabl2.setToolTipText("");
        jPanel5.add(jlabl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 30));

        fn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        fn.setAutoscrolls(false);
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel5.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 310, 30));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 130, 30));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("REGISTER");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 130, 30));

        jlabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(255, 255, 255));
        jlabel6.setText("Status :");
        jPanel5.add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 310, 20));

        jlabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(255, 255, 255));
        jlabel7.setText("Gender :");
        jPanel5.add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 310, 20));

        em.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        em.setAutoscrolls(false);
        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        jPanel5.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 310, 30));

        un.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        un.setAutoscrolls(false);
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel5.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 310, 30));

        jPanel1.add(jPanel5);
        jPanel5.setBounds(370, 0, 390, 600);

        name4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        name4.setText("NAME:");
        jPanel1.add(name4);
        name4.setBounds(0, 0, 56, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
          LOGINF If = new LOGINF();
          If.setVisible(true);
          this.dispose();     
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        if(fn.getText().isEmpty()||ln.getText().isEmpty()||em.getText().isEmpty()
                ||un.getText().isEmpty()||ps.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"All Fields are required!");
        }else if(ps.getText().length()<8){
        JOptionPane.showMessageDialog(null,"Password character should be 8 above");
        ps.setText("");
        }
          // Check if email is not a valid Gmail address
       else if (!em.getText().contains("@gmail.com")) {
        JOptionPane.showMessageDialog(null, "Please enter a valid Gmail address.");
        em.setText("");  // Optional: Clear the email field
            
        }else if(duplicateCheck()){
        System.out.println("duplicate Exist!");  
        }else{
              dbConnector dbc = new dbConnector();
              
        try{
            String pass = passwordHasher. hashPassword(ps.getText());
      
            String sql ="INSERT INTO tbl_student (s_fname, s_lname, s_email, s_username, s_password, s_gender, s_type, s_status,s_image, s_favsports)"
                + "VALUES('"+fn.getText()+"','"+ln.getText()+"','"+em.getText()+"','"
                  +un.getText()+"','"+pass+"','"+gn.getText()+"','"
                      +st.getSelectedItem()+"', 'Pending','"+destination+"', 'VB')";
        
         if(dbc.insertData(sql) ==1){
           JOptionPane.showMessageDialog(null,"Inserted Success!"); 
             LOGINF lf=new LOGINF ();
             lf.setVisible(true);
             this.dispose();
        }else{
          JOptionPane.showMessageDialog(null,"Registration Error"); 
                }
              }catch(NoSuchAlgorithmException ex){
                  System.out.println(""+ex);
              }
         }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField gn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabl1;
    private javax.swing.JLabel jlabl2;
    private javax.swing.JTextField ln;
    private javax.swing.JLabel name4;
    private javax.swing.JPasswordField ps;
    private javax.swing.JTextField ss;
    private javax.swing.JComboBox<String> st;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
