package Admin;
import user.usersForm;
import config.PanelPrinter;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import user.usersForm;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class individualPrinting extends javax.swing.JFrame {

    /**
     * Creates new form individualPrinting
     */
    public individualPrinting() {
        initComponents();
    }
    
    public static int getHeightFromWidth(String imagePath, int desiredWidth) {
        try {
            // Read the image file
            File imageFile = new File(imagePath);
            BufferedImage image = ImageIO.read(imageFile);
            
            // Get the original width and height of the image
            int originalWidth = image.getWidth();
            int originalHeight = image.getHeight();
            
            // Calculate the new height based on the desired width and the aspect ratio
            int newHeight = (int) ((double) desiredWidth / originalWidth * originalHeight);
            
            return newHeight;
        } catch (IOException ex) {
            System.out.println("No image found!");
        }
        
        return -1;
    }
    
    
    public  ImageIcon ResizeImage(String ImagePath, byte[] pic, JLabel label) {
    ImageIcon MyImage = null;
        if(ImagePath !=null){
            MyImage = new ImageIcon(ImagePath);
        }else{
            MyImage = new ImageIcon(pic);
        }
        
    int newHeight = getHeightFromWidth(ImagePath, label.getWidth());

    Image img = MyImage.getImage();
    Image newImg = img.getScaledInstance(label.getWidth(), newHeight, Image.SCALE_SMOOTH);
    ImageIcon image = new ImageIcon(newImg);
    return image;
}
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        page = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        em = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        sid = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        st = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ss = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("PRINTING FORMS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 250, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BACK");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(650, 0, 110, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 760, 60);

        page.setBackground(new java.awt.Color(255, 255, 255));
        page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GRADE TRACKER SYSTEM");
        page.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 410, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ivan villarino");
        page.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 230, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        page.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 86, 855, 16));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("First Name:");
        page.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 30));

        fn.setBackground(new java.awt.Color(51, 51, 51));
        fn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        fn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Last Name:");
        page.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 30));

        ln.setBackground(new java.awt.Color(51, 51, 51));
        ln.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        ln.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 160, 30));

        em.setBackground(new java.awt.Color(51, 51, 51));
        em.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        em.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 160, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Email:");
        page.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 30));

        gn.setBackground(new java.awt.Color(51, 51, 51));
        gn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        gn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(gn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 160, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("User Name:");
        page.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 30));

        un.setBackground(new java.awt.Color(51, 51, 51));
        un.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        un.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 160, 30));

        sid.setBackground(new java.awt.Color(51, 51, 51));
        sid.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        sid.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 160, 30));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("USER ID:");
        page.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 30));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Gender");
        page.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 100, 30));

        name7.setBackground(new java.awt.Color(51, 51, 51));
        name7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        name7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 349, 160, 30));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Account Type:");
        page.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 120, 30));

        st.setBackground(new java.awt.Color(51, 51, 51));
        st.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        st.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, 30));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText(" Status:");
        page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 30));

        image.setBackground(new java.awt.Color(0, 0, 0));
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        page.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 108, 350, 360));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-scorecard-64.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 68));

        page.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, 90));

        ss.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ss.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        page.add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 160, 30));

        jPanel1.add(page);
        page.setBounds(30, 120, 700, 550);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 80, 90, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        usersForm uf = new usersForm();
        uf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JPanel myPanel = new JPanel();
         PanelPrinter pPrint = new PanelPrinter(page);
         pPrint.printPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(individualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(individualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(individualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(individualPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new individualPrinting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel em;
    public javax.swing.JLabel fn;
    public javax.swing.JLabel gn;
    public javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel ln;
    public javax.swing.JLabel name7;
    private javax.swing.JPanel page;
    public javax.swing.JLabel sid;
    public javax.swing.JLabel ss;
    public javax.swing.JLabel st;
    public javax.swing.JLabel un;
    // End of variables declaration//GEN-END:variables
}
