package Admin;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import ivan.StudentForm;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import static com.sun.glass.ui.Cursor.setVisible;


/**
 *
 * @author Ivan
 */
public class userPage extends javax.swing.JInternalFrame {
    
     class maindesktop {

        public maindesktop() {
        }
    }
 
    /**
     * Creates new form userPage
     */
    public userPage() {
        initComponents();
        
        
        displayData();
 
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        search.setOpaque(false);
        search.setBackground(new Color(0,0,0,0));
      
    }
      public void displayData(){
      try{
          dbConnector dbc = new dbConnector();
          ResultSet rs = dbc.getData("SELECT*FROM tbl_student");
         tbl_student.setModel(DbUtils.resultSetToTableModel(rs));
          
          
      }catch(SQLException ex){
        System.out.println("Error:"+ex.getMessage());
      
      }
          
          
      }
    
    
    Color navcolor = new Color(0,51,102);
       Color headcolor = new Color(0,51,102);
       Color bodycolor = new Color(0,204,204);
      
      public String gender;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        cl1 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        cl2 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        cl5 = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        cl3 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        search_button = new javax.swing.JPanel();
        cl4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_student = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3);
        jPanel3.setBounds(550, 0, 170, 50);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("STUDENT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 390, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 50);

        add.setBackground(new java.awt.Color(0, 204, 204));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl1.setBackground(new java.awt.Color(0, 204, 204));
        cl1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cl1.setForeground(new java.awt.Color(255, 255, 255));
        cl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl1.setText("ADD");
        cl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cl1MouseExited(evt);
            }
        });
        add.add(cl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel1.add(add);
        add.setBounds(20, 80, 100, 40);

        edit.setBackground(new java.awt.Color(0, 204, 204));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl2.setBackground(new java.awt.Color(0, 204, 204));
        cl2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cl2.setForeground(new java.awt.Color(255, 255, 255));
        cl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl2.setText("EDIT");
        cl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cl2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cl2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cl2MouseExited(evt);
            }
        });
        edit.add(cl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel1.add(edit);
        edit.setBounds(140, 80, 100, 40);

        delete.setBackground(new java.awt.Color(0, 204, 204));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl5.setBackground(new java.awt.Color(0, 204, 204));
        cl5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cl5.setForeground(new java.awt.Color(255, 255, 255));
        cl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl5.setText("DELETE");
        cl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cl5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cl5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cl5MouseExited(evt);
            }
        });
        delete.add(cl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel1.add(delete);
        delete.setBounds(260, 80, 100, 40);

        refresh.setBackground(new java.awt.Color(0, 204, 204));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });
        refresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl3.setBackground(new java.awt.Color(0, 204, 204));
        cl3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cl3.setForeground(new java.awt.Color(255, 255, 255));
        cl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl3.setText("REFRESH");
        cl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cl3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cl3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cl3MouseExited(evt);
            }
        });
        refresh.add(cl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel1.add(refresh);
        refresh.setBounds(380, 80, 100, 40);

        search.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        search.setOpaque(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(550, 80, 200, 40);

        search_button.setBackground(new java.awt.Color(0, 204, 204));
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_buttonMouseExited(evt);
            }
        });
        search_button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cl4.setBackground(new java.awt.Color(0, 204, 204));
        cl4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cl4.setForeground(new java.awt.Color(255, 255, 255));
        cl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cl4.setText("SEARCH");
        cl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cl4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cl4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cl4MouseExited(evt);
            }
        });
        search_button.add(cl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel1.add(search_button);
        search_button.setBounds(770, 80, 100, 40);

        tbl_student.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tbl_student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_student);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 140, 850, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl1MouseClicked
        JFrame mainFrame =(JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.dispose();
        StudentForm sf = new StudentForm();
       sf.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cl1MouseClicked

    private void cl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl1MouseEntered
          add.setBackground(navcolor);
    }//GEN-LAST:event_cl1MouseEntered

    private void cl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl1MouseExited
       add.setBackground(bodycolor);
    }//GEN-LAST:event_cl1MouseExited

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
      add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
     add.setBackground(bodycolor);
    }//GEN-LAST:event_addMouseExited

    private void cl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl2MouseClicked
      int rowindex = tbl_student.getSelectedRow();
       if(rowindex < 0){
          JOptionPane.showMessageDialog(null,"Please select an Item");
       }else{
           TableModel model = tbl_student.getModel();
           StudentForm stf = new StudentForm();
           stf.st_id.setText(""+model.getValueAt(rowindex,0));
           stf. st_fname.setText(""+model.getValueAt(rowindex,1));   
           stf. st_lname.setText(""+model.getValueAt(rowindex,2));
           stf. st_email.setText(""+model.getValueAt(rowindex,3));
           stf. gender = model.getValueAt(rowindex,3).toString();
           stf. st_username.setText(""+model.getValueAt(rowindex,4));
           stf. st_password.setText(""+model.getValueAt(rowindex,5));
           stf. st_type.setText(""+model.getValueAt(rowindex,6));
          stf. st_status.setText(""+model.getValueAt(rowindex,7));
           String gend = model.getValueAt(rowindex,8).toString();
           
           if(gend.equals("Male")){
              stf.male.setSelected(true);
           }
            if(gend.equals("Female")){
              stf.female.setSelected(true);
              
        }
           stf.setVisible(true); 
           stf.st_label.setText("UPDATE");
           JFrame mainFrame =(JFrame) SwingUtilities.getWindowAncestor(this);
           mainFrame.dispose();
       }

    }//GEN-LAST:event_cl2MouseClicked

    private void cl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl2MouseEntered
        edit.setBackground(navcolor);
    }//GEN-LAST:event_cl2MouseEntered

    private void cl2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl2MouseExited
         edit.setBackground(bodycolor);
    }//GEN-LAST:event_cl2MouseExited

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        edit.setBackground(navcolor);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
    edit.setBackground(bodycolor);
    }//GEN-LAST:event_editMouseExited

    private void cl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl3MouseClicked
      
    }//GEN-LAST:event_cl3MouseClicked

    private void cl3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl3MouseEntered
         refresh.setBackground(navcolor);
    }//GEN-LAST:event_cl3MouseEntered

    private void cl3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl3MouseExited
         refresh.setBackground(bodycolor);
    }//GEN-LAST:event_cl3MouseExited

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setBackground(bodycolor);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
         refresh.setBackground(bodycolor);
    }//GEN-LAST:event_refreshMouseExited

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void cl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cl4MouseClicked

    private void cl4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl4MouseEntered
      search_button.setBackground(navcolor);
    }//GEN-LAST:event_cl4MouseEntered

    private void cl4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl4MouseExited
      search_button.setBackground(bodycolor);
    }//GEN-LAST:event_cl4MouseExited

    private void search_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseEntered
        search_button.setBackground(navcolor);
    }//GEN-LAST:event_search_buttonMouseEntered

    private void search_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseExited
        search_button.setBackground(bodycolor);
    }//GEN-LAST:event_search_buttonMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
       JFrame mainFrame =(JFrame) SwingUtilities.getWindowAncestor(this);
        mainFrame.dispose();
        StudentForm stf = new StudentForm();
        stf.setVisible(true);
        stf. action = "Add";
        stf. st_label.setText("SAVE");
    }//GEN-LAST:event_addMouseClicked

    private void cl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cl5MouseClicked

    private void cl5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cl5MouseEntered

    private void cl5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cl5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cl5MouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseExited

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
      displayData();
    }//GEN-LAST:event_refreshMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
    int rowindex = tbl_student.getSelectedRow();
       if(rowindex < 0){
          JOptionPane.showMessageDialog(null,"Please select an Item");
       }else{
           TableModel model = tbl_student.getModel();
           StudentForm stf = new StudentForm();
           stf.st_id.setText(""+model.getValueAt(rowindex,0));
           stf. st_fname.setText(""+model.getValueAt(rowindex,1));   
           stf. st_lname.setText(""+model.getValueAt(rowindex,2));
           stf. st_email.setText(""+model.getValueAt(rowindex,3));
           stf. gender = model.getValueAt(rowindex,3).toString();
           stf. st_username.setText(""+model.getValueAt(rowindex,4));
           stf. st_password.setText(""+model.getValueAt(rowindex,5));
           stf. st_type.setText(""+model.getValueAt(rowindex,6));
          stf. st_status.setText(""+model.getValueAt(rowindex,7));
           String gend = model.getValueAt(rowindex,8).toString();
           
           if(gend.equals("Male")){
              stf.male.setSelected(true);
           }
            if(gend.equals("Female")){
              stf.female.setSelected(true);
              
        }
           stf.setVisible(true); 
           stf.st_label.setText("UPDATE");
           JFrame mainFrame =(JFrame) SwingUtilities.getWindowAncestor(this);
           mainFrame.dispose();
       }
    }//GEN-LAST:event_editMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.JLabel cl1;
    private javax.swing.JLabel cl2;
    private javax.swing.JLabel cl3;
    private javax.swing.JLabel cl4;
    private javax.swing.JLabel cl5;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel refresh;
    private javax.swing.JTextField search;
    private javax.swing.JPanel search_button;
    private javax.swing.JTable tbl_student;
    // End of variables declaration//GEN-END:variables

   

   
}
